### ISSUE TITLE
Questions and suggestions

### ISSUE THREAD

**Issue by IngwiePhoenix** [rogerpoon/jspp#33]
Hey there.

On my go of exploring JavaScript-ish languages,  I came across this language. And so far, I really like what it looks like! Therefore I'd like to make a few suggestions and ask a few questions also.

First suggestion is: **Named parameters**. This is something that always bothers me in JS:
```
myfunc({
    foo: "bar",
    id: 3
});
// ...
function myfunc(o) {
    if(typeof o.name == "string" && typeof o.id != "undefined")
        // Code...
    else throw new Error("Arguments supplied wrongly.");
}
```

And this is only a very simple case here... So I'd like to suggest a named parameter capability:

```
function myfunc(name, id) { ... }
myfunc(name: "Bob", id: 9):
```

The AngelScript language for C++ supports this feature by using a smart parser. It sees the colon in the function list and maps the call from name to name - at least, that is how I understood it. If it is exactly like that, I don't know.

Anyway it'd be really cool if this would go into JSPP.

Next on I'd like to ask if JSPP will support the detection of unused functions, classes and other parts, in order to optimize the final code.

Once JSPP reaches a more suitable stage - from the thin README, I am guessing its still under heavy development - I will be making a [WebPack](https://github.com/webpack/webpack) loader, that allows JSPP files to be loaded by Webpack.

I singed up for the newsletter and I am looking forward for JSPP! Kind regards, Ingwie =)

**Comment by IngwiePhoenix** [comment]
I almost forgot - operator overloading. Will this be made possible also?

**Comment by rogerpoon** [comment]
>First suggestion is: Named parameters. This is something that always bothers me in JS

We already support function overloading so this would be redundant and require changes to the parser, pushing release dates back further. It is not a priority, and, as you've mentioned, this is more or less already accomplished in JavaScript using the object literal syntax. It is, frankly, just two more characters to type (`{` and `}`).

>Next on I'd like to ask if JSPP will support the detection of unused functions, classes and other parts, in order to optimize the final code.

Yes, this is already complete.

>I almost forgot - operator overloading. Will this be made possible also?

Unfortunately, no.

**Comment by IngwiePhoenix** [comment]
Ah okay, thanks for the reply. :)

Since you are to support a C# like syntax, will this include LINQ?

**Comment by IngwiePhoenix** [comment]
Beep. Just wanted to close the issue since its not really an issue, and wish you good luck with developing this. Still looking forward to it. :)
